name: Air Quality Daily Report

on:
  schedule:
    # เวลา UTC (ไทยลบออก 7 ชม.)
    # 07:00 TH = 00:00 UTC
    # 12:00 TH = 05:00 UTC
    # 15:00 TH = 08:00 UTC
    # 17:00 TH = 10:00 UTC
    - cron: '0 0,5,8,10 * * *'
  workflow_dispatch: 

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bot Script
        env:
          AIR4THAI_KEY: ${{ secrets.AIR4THAI_KEY }}
          GISTDA_API_KEY: ${{ secrets.GISTDA_API_KEY }}
          TMD_3HR_KEY: ${{ secrets.TMD_3HR_KEY }} # ✅ แมพไปหา Secret ตัวใหม่
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python bot.py
